// Tool configurations for ElevenLabs agent
export const toolsConfig = [
  {
    id: "1",
    name: "Create/Update File",
    description: "Create a new file or update an existing file in the project",
    filename: "tool1_create_update_file.json",
    config: {
      type: "webhook",
      name: "create_or_update_file",
      description: "Create a new file or update an existing file in the project. Use this when the user wants to generate new code or modify existing code. Always provide complete, working code in the file_content parameter.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/webhooks/elevenlabs",
        method: "POST",
        path_params_schema: [],
        query_params_schema: [],
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing file action details",
          required: true,
          properties: [
            {
              id: "action_type",
              type: "string",
              description: "The action to perform. Must be either 'create' for new files or 'update' for existing files.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "file_path",
              type: "string",
              description: "The file path relative to project root (e.g., 'src/components/Button.tsx', 'utils/helpers.js'). Always include the full path with file extension.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "file_content",
              type: "string",
              description: "The complete file content including all code, imports, and comments. This must be the full, working code - not a snippet or partial code.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "project_id",
              type: "string",
              description: "The Appwrite project ID",
              dynamic_variable: "",
              constant_value: "68c9f40a002d5afe6b43",
              value_type: "constant",
              required: true,
            },
            {
              id: "description",
              type: "string",
              description: "Brief description of what the code does (optional)",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: false,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [],
        auth_connection: null,
      },
      response_timeout_secs: 30,
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "2",
    name: "Delete File",
    description: "Delete a file or folder from the project",
    filename: "tool2_delete_file.json",
    config: {
      type: "webhook",
      name: "delete_file",
      description: "Delete a file or folder from the project. Use this when the user wants to remove a file or clean up the project structure.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/webhooks/elevenlabs",
        method: "POST",
        path_params_schema: [],
        query_params_schema: [],
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing delete action details",
          required: true,
          properties: [
            {
              id: "action_type",
              type: "string",
              description: "The action type, always 'delete' for this tool",
              dynamic_variable: "",
              constant_value: "delete",
              value_type: "constant",
              required: true,
            },
            {
              id: "file_path",
              type: "string",
              description: "The file or folder path to delete (e.g., 'src/components/Button.tsx' or 'src/utils/'). If deleting a folder, set is_folder to true.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "project_id",
              type: "string",
              description: "The Appwrite project ID",
              dynamic_variable: "",
              constant_value: "68c9f40a002d5afe6b43",
              value_type: "constant",
              required: true,
            },
            {
              id: "is_folder",
              type: "boolean",
              description: "Set to true if deleting a folder, false if deleting a file. Defaults to false if not specified.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: false,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [],
        auth_connection: null,
      },
      response_timeout_secs: 20,
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "3",
    name: "Rename File",
    description: "Rename a file or folder in the project",
    filename: "tool3_rename_file.json",
    config: {
      type: "webhook",
      name: "rename_file",
      description: "Rename a file or folder in the project. Use this when the user wants to change a file name or reorganize the project structure.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/webhooks/elevenlabs",
        method: "POST",
        path_params_schema: [],
        query_params_schema: [],
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing rename action details",
          required: true,
          properties: [
            {
              id: "action_type",
              type: "string",
              description: "The action type, always 'rename' for this tool",
              dynamic_variable: "",
              constant_value: "rename",
              value_type: "constant",
              required: true,
            },
            {
              id: "file_path",
              type: "string",
              description: "The current file or folder path (e.g., 'src/components/OldButton.tsx')",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "new_path",
              type: "string",
              description: "The new file or folder path (e.g., 'src/components/NewButton.tsx'). Must include the full path with file extension.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "project_id",
              type: "string",
              description: "The Appwrite project ID",
              dynamic_variable: "",
              constant_value: "68c9f40a002d5afe6b43",
              value_type: "constant",
              required: true,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [],
        auth_connection: null,
      },
      response_timeout_secs: 20,
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "4",
    name: "Get Project Files",
    description: "Get a list of all files in the project or read a specific file's content",
    filename: "tool4_get_project_files.json",
    config: {
      type: "webhook",
      name: "get_project_files",
      description: "Get a list of all files in the project or read a specific file's content. Use this to understand the existing codebase before making changes. Always check existing files before modifying them to preserve existing code and imports.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/files",
        method: "GET",
        path_params_schema: [],
        query_params_schema: [
          {
            id: "projectId",
            type: "string",
            description: "The Appwrite project ID",
            dynamic_variable: "",
            constant_value: "68c9f40a002d5afe6b43",
            value_type: "constant",
            required: true,
          },
          {
            id: "path",
            type: "string",
            description: "Optional: Specific file path to read. If omitted, returns all files in the project.",
            dynamic_variable: "",
            constant_value: "",
            value_type: "llm_prompt",
            required: false,
          },
        ],
        request_body_schema: null,
        request_headers: [],
        auth_connection: null,
      },
      response_timeout_secs: 20,
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: "auto",
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
  {
    id: "5",
    name: "Generate Code with Context",
    description: "Intelligently generate or modify code based on user's request with full project context",
    filename: "tool_code_generation.json",
    config: {
      type: "webhook",
      name: "generate_code_with_context",
      description: "Intelligently generate or modify code based on user's request. This tool analyzes the project context, identifies relevant files, formulates a plan, and generates complete working code. Use this for any code generation task - it will automatically find and update the right files.",
      api_schema: {
        url: "https://code-easy-gamma.vercel.app/api/webhooks/elevenlabs/code-generation",
        method: "POST",
        path_params_schema: [],
        query_params_schema: [],
        request_body_schema: {
          id: "body",
          type: "object",
          description: "The request body containing code generation details",
          required: true,
          properties: [
            {
              id: "user_request",
              type: "string",
              description: "The user's coding request or task description. Be specific about what code needs to be generated or modified.",
              dynamic_variable: "",
              constant_value: "",
              value_type: "llm_prompt",
              required: true,
            },
            {
              id: "project_id",
              type: "string",
              description: "The Appwrite project ID. Use the value from the conversation context or userId.",
              dynamic_variable: "",
              constant_value: "68c9f40a002d5afe6b43",
              value_type: "constant",
              required: true,
            },
          ],
          dynamic_variable: "",
          constant_value: "",
          value_type: "llm_prompt",
        },
        request_headers: [],
        auth_connection: null,
      },
      response_timeout_secs: 60,
      assignments: [],
      disable_interruptions: false,
      force_pre_tool_speech: false,
      tool_call_sound: null,
      tool_call_sound_behavior: "auto",
      execution_mode: "immediate",
      dynamic_variables: {
        dynamic_variable_placeholders: {},
      },
    },
  },
] as const;

